---
# For configuration options and examples, please see:
# https://getbulby.dev/en/configs/services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Bulby is awesome

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Bulby is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Bulby is 😎
